import asyncio
import sys
from datetime import datetime
from motor.motor_asyncio import AsyncIOMotorClient

# Add workspace path to sys.path so we can import from app
sys.path.append("/workspace")

from app.config import settings

# Default keywords list (updated with trial/start of operation terms)
DEFAULT_KEYWORDS = [
    # ── Từ khóa cũ ──
    "sân bay Long Thành",
    "gói thầu 5.10",
    "gói thầu 4.6",
    "Vietur",
    "bụi đỏ",
    "giải phóng mặt bằng",
    "ACV",
    "nhà ga hành khách",
    "đường băng Long Thành",
    "tái định cư Lộc An",
    "tiến độ Long Thành",
    "thu hồi đất Long Thành",
    "giao thông kết nối Long Thành",
    "đóng điện sân bay Long Thành",
    "gói thầu sân bay",
    "tổng công ty cảng hàng không",
    "khởi công Long Thành",
    "khánh thành Long Thành",
    "đường cất hạ cánh",
    "tháp không lưu Long Thành",
    
    # ── Chuẩn bị khai thác ──
    "chuẩn bị khai thác sân bay Long Thành",
    "chuẩn bị khai thác Long Thành",
    "phương án khai thác Long Thành",
    "quy trình khai thác Long Thành",
    "kế hoạch vận hành Long Thành",
    "đào tạo vận hành Long Thành",
    "công tác chuẩn bị khai thác",
    "chuyển giao khai thác Long Thành",
    
    # ── Khai thác thử / Bay thử / Nghiệm thu ──
    "khai thác thử sân bay Long Thành",
    "khai thác thử Long Thành",
    "bay thử sân bay Long Thành",
    "bay thử Long Thành",
    "bay hiệu chuẩn Long Thành",
    "vận hành thử Long Thành",
    "chạy thử nhà ga Long Thành",
    "chạy thử sân bay Long Thành",
    "diễn tập khai thác Long Thành",
    "hoạt động thử nghiệm Long Thành",
    "bay kiểm nghiệm Long Thành",
    
    # ── Bắt đầu khai thác / Vận hành thương mại ──
    "khai thác thương mại Long Thành",
    "mở cửa sân bay Long Thành",
    "bắt đầu khai thác Long Thành",
    "cấp phép khai thác Long Thành",
    "khai trương sân bay Long Thành",
    "vận hành thương mại Long Thành",
    "đón chuyến bay đầu tiên Long Thành",
    "chuyến bay đầu tiên sân bay Long Thành",
    "ngày khai thác sân bay Long Thành"
]

# Default sources list (expanded to cover all categories for each source)
DEFAULT_SOURCES = [
    {"name": "VnExpress Tag - Sân bay Long Thành", "url": "https://vnexpress.net/tag/san-bay-long-thanh-216912", "source_type": "WEB"},
    {"name": "Tuổi Trẻ Chủ đề - Sân bay Long Thành", "url": "https://tuoitre.vn/chu-de/san-bay-long-thanh.html", "source_type": "WEB"},
    {"name": "Báo Giao thông - Tìm kiếm Long Thành", "url": "https://www.baogiaothong.vn/tim-kiem.html?q=s%C3%A2n+bay+Long+Th%C3%A0nh", "source_type": "WEB"},
    {"name": "VietnamNet Tag - Sân bay Long Thành", "url": "https://vietnamnet.vn/san-bay-long-thanh-tag8279442006764491745.html", "source_type": "WEB"},
    {"name": "Dân Trí - Trang chủ", "url": "https://dantri.com.vn/rss/home.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Sự kiện", "url": "https://dantri.com.vn/rss/su-kien.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Thời sự", "url": "https://dantri.com.vn/rss/thoi-su.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Thế giới", "url": "https://dantri.com.vn/rss/the-gioi.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Giá vàng", "url": "https://dantri.com.vn/rss/gia-vang.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Đời sống", "url": "https://dantri.com.vn/rss/doi-song.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Thể thao", "url": "https://dantri.com.vn/rss/the-thao.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Lao động - Việc làm", "url": "https://dantri.com.vn/rss/lao-dong-viec-lam.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Giáo dục", "url": "https://dantri.com.vn/rss/giao-duc.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Tấm lòng nhân ái", "url": "https://dantri.com.vn/rss/tam-long-nhan-ai.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Kinh doanh", "url": "https://dantri.com.vn/rss/kinh-doanh.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Bất động sản", "url": "https://dantri.com.vn/rss/bat-dong-san.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Giải trí", "url": "https://dantri.com.vn/rss/giai-tri.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Du lịch", "url": "https://dantri.com.vn/rss/du-lich.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Pháp luật", "url": "https://dantri.com.vn/rss/phap-luat.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Sức khỏe", "url": "https://dantri.com.vn/rss/suc-khoe.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Công nghệ", "url": "https://dantri.com.vn/rss/cong-nghe.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Ô tô - Xe máy", "url": "https://dantri.com.vn/rss/o-to-xe-may.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Tình yêu - Giới tính", "url": "https://dantri.com.vn/rss/tinh-yeu-gioi-tinh.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Khoa học", "url": "https://dantri.com.vn/rss/khoa-hoc.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Nội vụ", "url": "https://dantri.com.vn/rss/noi-vu.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Bạn đọc", "url": "https://dantri.com.vn/rss/ban-doc.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Tâm điểm", "url": "https://dantri.com.vn/rss/tam-diem.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Dmagazine", "url": "https://dantri.com.vn/rss/dmagazine.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Infographic", "url": "https://dantri.com.vn/rss/infographic.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Photo News", "url": "https://dantri.com.vn/rss/photo-news.rss", "source_type": "RSS"},
    {"name": "Dân Trí - DNews", "url": "https://dantri.com.vn/rss/dnews.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Tọa đàm trực tuyến", "url": "https://dantri.com.vn/rss/toa-dam-truc-tuyen.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Xổ số", "url": "https://dantri.com.vn/rss/xo-so.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Interactive", "url": "https://dantri.com.vn/rss/interactive.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Tết", "url": "https://dantri.com.vn/rss/tet.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Photo Story", "url": "https://dantri.com.vn/rss/photo-story.rss", "source_type": "RSS"},
    {"name": "Dân Trí - D-Buzz", "url": "https://dantri.com.vn/rss/d-buzz.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Thời tiết", "url": "https://dantri.com.vn/rss/thoi-tiet.rss", "source_type": "RSS"},
    {"name": "Dân Trí - DT360", "url": "https://dantri.com.vn/rss/dt360.rss", "source_type": "RSS"},
    {"name": "Dân Trí - Rss.Htm", "url": "https://dantri.com.vn/rss.htm", "source_type": "RSS"},
    {"name": "VietnamNet - Rss", "url": "https://infonet.vietnamnet.vn/rss", "source_type": "RSS"},
    {"name": "VietnamNet - Đời sống", "url": "https://infonet.vietnamnet.vn/rss/doi-song.rss", "source_type": "RSS"},
    {"name": "VietnamNet - Thị trường", "url": "https://infonet.vietnamnet.vn/rss/thi-truong.rss", "source_type": "RSS"},
    {"name": "VietnamNet - Thế giới", "url": "https://infonet.vietnamnet.vn/rss/the-gioi.rss", "source_type": "RSS"},
    {"name": "VietnamNet - Gia đình", "url": "https://infonet.vietnamnet.vn/rss/gia-dinh.rss", "source_type": "RSS"},
    {"name": "VietnamNet - Giới trẻ", "url": "https://infonet.vietnamnet.vn/rss/gioi-tre.rss", "source_type": "RSS"},
    {"name": "VietnamNet - Khỏe - Đẹp", "url": "https://infonet.vietnamnet.vn/rss/khoe-dep.rss", "source_type": "RSS"},
    {"name": "VietnamNet - Chuyện lạ", "url": "https://infonet.vietnamnet.vn/rss/chuyen-la.rss", "source_type": "RSS"},
    {"name": "VietnamNet - Quân sự", "url": "https://infonet.vietnamnet.vn/rss/quan-su.rss", "source_type": "RSS"},
    {"name": "VNExpress - Thế giới", "url": "https://vnexpress.net/rss/the-gioi.rss", "source_type": "RSS"},
    {"name": "VNExpress - Thời sự", "url": "https://vnexpress.net/rss/thoi-su.rss", "source_type": "RSS"},
    {"name": "VNExpress - Kinh doanh", "url": "https://vnexpress.net/rss/kinh-doanh.rss", "source_type": "RSS"},
    {"name": "VNExpress - Giải trí", "url": "https://vnexpress.net/rss/giai-tri.rss", "source_type": "RSS"},
    {"name": "VNExpress - Thể thao", "url": "https://vnexpress.net/rss/the-thao.rss", "source_type": "RSS"},
    {"name": "VNExpress - Pháp luật", "url": "https://vnexpress.net/rss/phap-luat.rss", "source_type": "RSS"},
    {"name": "VNExpress - Giáo dục", "url": "https://vnexpress.net/rss/giao-duc.rss", "source_type": "RSS"},
    {"name": "VNExpress - Góc nhìn", "url": "https://vnexpress.net/rss/goc-nhin.rss", "source_type": "RSS"},
    {"name": "VNExpress - Bất động sản", "url": "https://vnexpress.net/rss/bat-dong-san.rss", "source_type": "RSS"},
    {"name": "VNExpress - Tin mới nhất", "url": "https://vnexpress.net/rss/tin-moi-nhat.rss", "source_type": "RSS"},
    {"name": "VNExpress - Tin nổi bật", "url": "https://vnexpress.net/rss/tin-noi-bat.rss", "source_type": "RSS"},
    {"name": "VNExpress - Sức khỏe", "url": "https://vnexpress.net/rss/suc-khoe.rss", "source_type": "RSS"},
    {"name": "VNExpress - Đời sống", "url": "https://vnexpress.net/rss/gia-dinh.rss", "source_type": "RSS"},
    {"name": "VNExpress - Du lịch", "url": "https://vnexpress.net/rss/du-lich.rss", "source_type": "RSS"},
    {"name": "VNExpress - Khoa học công nghệ", "url": "https://vnexpress.net/rss/khoa-hoc-cong-nghe.rss", "source_type": "RSS"},
    {"name": "VNExpress - Xe", "url": "https://vnexpress.net/rss/oto-xe-may.rss", "source_type": "RSS"},
    {"name": "VNExpress - Ý kiến", "url": "https://vnexpress.net/rss/y-kien.rss", "source_type": "RSS"},
    {"name": "VNExpress - Tâm sự", "url": "https://vnexpress.net/rss/tam-su.rss", "source_type": "RSS"},
    {"name": "VNExpress - VnE-GO", "url": "https://vnexpress.net/rss/vne-go.rss", "source_type": "RSS"},
    {"name": "VNExpress - Thư giãn", "url": "https://vnexpress.net/rss/thu-gian.rss", "source_type": "RSS"},
    {"name": "VNExpress - Spotlight", "url": "https://vnexpress.net/rss/spotlight.rss", "source_type": "RSS"},
    {"name": "VNExpress - Tin xem nhiều", "url": "https://vnexpress.net/rss/tin-xem-nhieu.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Đăng nhập", "url": "https://my.thanhnien.vn/page/login.html?redirect_url=https://thanhnien.vn/rss.html", "source_type": "RSS"},
    {"name": "Thanh Niên - Trang chủ", "url": "https://thanhnien.vn/rss/home.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thời sự", "url": "https://thanhnien.vn/rss/thoi-su.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Pháp luật", "url": "https://thanhnien.vn/rss/thoi-su/phap-luat.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Dân sinh", "url": "https://thanhnien.vn/rss/thoi-su/dan-sinh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Lao động - Việc làm", "url": "https://thanhnien.vn/rss/thoi-su/lao-dong-viec-lam.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Quyền được biết", "url": "https://thanhnien.vn/rss/thoi-su/quyen-duoc-biet.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Phóng sự / Điều tra", "url": "https://thanhnien.vn/rss/thoi-su/phong-su--dieu-tra.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Quốc phòng", "url": "https://thanhnien.vn/rss/thoi-su/quoc-phong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Chống tin giả", "url": "https://thanhnien.vn/rss/thoi-su/chong-tin-gia.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thành tựu y khoa", "url": "https://thanhnien.vn/rss/thoi-su/thanh-tuu-y-khoa.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Chính trị", "url": "https://thanhnien.vn/rss/chinh-tri.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Sự kiện", "url": "https://thanhnien.vn/rss/chinh-tri/su-kien.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Vươn mình trong kỷ nguyên mới", "url": "https://thanhnien.vn/rss/chinh-tri/vuon-minh-trong-ky-nguyen-moi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thời luận", "url": "https://thanhnien.vn/rss/chinh-tri/thoi-luan.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Đại hội XI Mặt trận tổ quốc Việt Nam", "url": "https://thanhnien.vn/rss/chinh-tri/dai-hoi-xi-mat-tran-to-quoc-viet-nam.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Ngày hội bầu cử", "url": "https://thanhnien.vn/rss/chinh-tri/ngay-hoi-bau-cu.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Chào ngày mới", "url": "https://thanhnien.vn/rss/chao-ngay-moi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thế giới", "url": "https://thanhnien.vn/rss/the-gioi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Kinh tế thế giới", "url": "https://thanhnien.vn/rss/the-gioi/kinh-te-the-gioi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Quân sự", "url": "https://thanhnien.vn/rss/the-gioi/quan-su.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Góc nhìn", "url": "https://thanhnien.vn/rss/the-gioi/goc-nhin.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Hồ sơ", "url": "https://thanhnien.vn/rss/the-gioi/ho-so.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Người Việt năm châu", "url": "https://thanhnien.vn/rss/the-gioi/nguoi-viet-nam-chau.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Chuyện lạ", "url": "https://thanhnien.vn/rss/the-gioi/chuyen-la.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Kinh tế", "url": "https://thanhnien.vn/rss/kinh-te.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Kinh tế xanh", "url": "https://thanhnien.vn/rss/kinh-te/kinh-te-xanh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Chính sách - Phát triển", "url": "https://thanhnien.vn/rss/kinh-te/chinh-sach-phat-trien.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Ngân hàng", "url": "https://thanhnien.vn/rss/kinh-te/ngan-hang.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Chứng khoán", "url": "https://thanhnien.vn/rss/kinh-te/chung-khoan.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Doanh nghiệp", "url": "https://thanhnien.vn/rss/kinh-te/doanh-nghiep.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Khát vọng Việt Nam", "url": "https://thanhnien.vn/rss/kinh-te/doanh-nhan.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Làm giàu", "url": "https://thanhnien.vn/rss/kinh-te/lam-giau.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Địa ốc", "url": "https://thanhnien.vn/rss/kinh-te/dia-oc.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Đời sống", "url": "https://thanhnien.vn/rss/doi-song.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - và tôi", "url": "https://thanhnien.vn/rss/doi-song/thanh-nien-va-toi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tết yêu thương", "url": "https://thanhnien.vn/rss/doi-song/tet-yeu-thuong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Người sống quanh ta", "url": "https://thanhnien.vn/rss/doi-song/nguoi-song-quanh-ta.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Gia đình", "url": "https://thanhnien.vn/rss/doi-song/gia-dinh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Ẩm thực", "url": "https://thanhnien.vn/rss/doi-song/am-thuc.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Cộng đồng", "url": "https://thanhnien.vn/rss/doi-song/cong-dong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Một nửa thế giới", "url": "https://thanhnien.vn/rss/doi-song/mot-nua-the-gioi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Khát vọng năm rồng", "url": "https://thanhnien.vn/rss/doi-song/khat-vong-nam-rong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Sức khỏe", "url": "https://thanhnien.vn/rss/suc-khoe.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Khỏe đẹp mỗi ngày", "url": "https://thanhnien.vn/rss/suc-khoe/khoe-dep-moi-ngay.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Làm đẹp", "url": "https://thanhnien.vn/rss/suc-khoe/lam-dep.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Giới tính", "url": "https://thanhnien.vn/rss/suc-khoe/gioi-tinh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Y tế thông minh", "url": "https://thanhnien.vn/rss/suc-khoe/y-te-thong-minh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thẩm mỹ an toàn", "url": "https://thanhnien.vn/rss/suc-khoe/tham-my-an-toan.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tin hay y tế", "url": "https://thanhnien.vn/rss/suc-khoe/tin-hay-y-te.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Giới trẻ", "url": "https://thanhnien.vn/rss/gioi-tre.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Sống - Yêu - Ăn - Chơi", "url": "https://thanhnien.vn/rss/gioi-tre/song-yeu-an-choi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tiếp sức gen Z mùa thi", "url": "https://thanhnien.vn/rss/gioi-tre/tiep-suc-gen-z-mua-thi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Cơ hội nghề nghiệp", "url": "https://thanhnien.vn/rss/gioi-tre/co-hoi-nghe-nghiep.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Đoàn - Hội", "url": "https://thanhnien.vn/rss/gioi-tre/doan-hoi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Kết nối", "url": "https://thanhnien.vn/rss/gioi-tre/ket-noi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Khởi nghiệp", "url": "https://thanhnien.vn/rss/gioi-tre/khoi-nghiep.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thế giới mạng", "url": "https://thanhnien.vn/rss/gioi-tre/the-gioi-mang.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Gương mặt trẻ", "url": "https://thanhnien.vn/rss/gioi-tre/guong-mat-tre.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tiêu dùng thông minh", "url": "https://thanhnien.vn/rss/tieu-dung-thong-minh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Mới- Mới- Mới", "url": "https://thanhnien.vn/rss/tieu-dung-thong-minh/moi-moi-moi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Mua một chạm", "url": "https://thanhnien.vn/rss/tieu-dung-thong-minh/mua-mot-cham.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Ở đâu rẻ?", "url": "https://thanhnien.vn/rss/tieu-dung-thong-minh/o-dau-re.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Góc người tiêu dùng", "url": "https://thanhnien.vn/rss/tieu-dung-thong-minh/goc-nguoi-tieu-dung.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Giáo dục", "url": "https://thanhnien.vn/rss/giao-duc.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tuyển sinh", "url": "https://thanhnien.vn/rss/giao-duc/tuyen-sinh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Chọn nghề - Chọn trường", "url": "https://thanhnien.vn/rss/giao-duc/chon-nghe-chon-truong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Du học", "url": "https://thanhnien.vn/rss/giao-duc/du-hoc.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Nhà trường", "url": "https://thanhnien.vn/rss/giao-duc/nha-truong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Phụ huynh", "url": "https://thanhnien.vn/rss/giao-duc/phu-huynh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tra cứu điểm thi", "url": "https://thanhnien.vn/rss/giao-duc/tra-cuu-diem-thi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Ôn thi tốt nghiệp", "url": "https://thanhnien.vn/rss/giao-duc/on-thi-tot-nghiep.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Du lịch", "url": "https://thanhnien.vn/rss/du-lich.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tin tức - Sự kiện", "url": "https://thanhnien.vn/rss/du-lich/tin-tuc-su-kien.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Chơi gì, ăn đâu, đi thế nào?", "url": "https://thanhnien.vn/rss/du-lich/choi-gi-an-dau-di-the-nao.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Bất động sản du lịch", "url": "https://thanhnien.vn/rss/du-lich/bat-dong-san-du-lich.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Câu chuyện du lịch", "url": "https://thanhnien.vn/rss/du-lich/cau-chuyen-du-lich.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Khám phá", "url": "https://thanhnien.vn/rss/du-lich/kham-pha.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Văn hóa", "url": "https://thanhnien.vn/rss/van-hoa.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Sống đẹp", "url": "https://thanhnien.vn/rss/van-hoa/song-dep.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Câu chuyện văn hóa", "url": "https://thanhnien.vn/rss/van-hoa/cau-chuyen-van-hoa.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Khảo cứu", "url": "https://thanhnien.vn/rss/van-hoa/khao-cuu.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Xem - Nghe", "url": "https://thanhnien.vn/rss/van-hoa/xem-nghe.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Sách hay", "url": "https://thanhnien.vn/rss/van-hoa/sach-hay.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Món ngon Hà Nội", "url": "https://thanhnien.vn/rss/van-hoa/mon-ngon-ha-noi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Nghĩa tình miền Tây", "url": "https://thanhnien.vn/rss/van-hoa/nghia-tinh-mien-tay.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Hào khí miền Đông", "url": "https://thanhnien.vn/rss/van-hoa/hao-khi-mien-dong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Giải trí", "url": "https://thanhnien.vn/rss/giai-tri.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Phim", "url": "https://thanhnien.vn/rss/giai-tri/phim.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Truyền hình", "url": "https://thanhnien.vn/rss/giai-tri/truyen-hinh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Đời nghệ sĩ", "url": "https://thanhnien.vn/rss/giai-tri/doi-nghe-si.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thể thao", "url": "https://thanhnien.vn/rss/the-thao.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - World Cup 2026", "url": "https://thanhnien.vn/rss/the-thao/world-cup-2026.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Bóng đá  Sinh viên", "url": "https://thanhnien.vn/rss/the-thao/bong-da-thanh-nien-sinh-vien.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Bóng đá Việt Nam", "url": "https://thanhnien.vn/rss/the-thao/bong-da-viet-nam.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Bóng đá Quốc tế", "url": "https://thanhnien.vn/rss/the-thao/bong-da-quoc-te.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thể thao & Cộng đồng", "url": "https://thanhnien.vn/rss/the-thao/the-thao-cong-dong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Các môn khác", "url": "https://thanhnien.vn/rss/the-thao/cac-mon-khac.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Công nghệ", "url": "https://thanhnien.vn/rss/cong-nghe.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tin tức công nghệ", "url": "https://thanhnien.vn/rss/cong-nghe/tin-tuc-cong-nghe.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Blockchain", "url": "https://thanhnien.vn/rss/cong-nghe/blockchain.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Sản phẩm", "url": "https://thanhnien.vn/rss/cong-nghe/san-pham.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Xu hướng - Chuyển đổi số", "url": "https://thanhnien.vn/rss/cong-nghe/xu-huong-chuyen-doi-so.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thủ thuật", "url": "https://thanhnien.vn/rss/cong-nghe/thu-thuat.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Game", "url": "https://thanhnien.vn/rss/cong-nghe/game.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Xe", "url": "https://thanhnien.vn/rss/xe.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thị trường", "url": "https://thanhnien.vn/rss/xe/thi-truong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Xe xanh", "url": "https://thanhnien.vn/rss/xe/xe-xanh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Đánh giá xe", "url": "https://thanhnien.vn/rss/xe/danh-gia-xe.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tư vấn", "url": "https://thanhnien.vn/rss/xe/tu-van.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Video", "url": "https://thanhnien.vn/rss/xe/video.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Diễn đàn", "url": "https://thanhnien.vn/rss/xe/dien-dan.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Xe - Giao thông", "url": "https://thanhnien.vn/rss/xe/xe-giao-thong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thời trang trẻ", "url": "https://thanhnien.vn/rss/thoi-trang-tre.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thời trang 24/7", "url": "https://thanhnien.vn/rss/thoi-trang-tre/thoi-trang-247.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Giữ dáng", "url": "https://thanhnien.vn/rss/thoi-trang-tre/giu-dang.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thời trang nghề & nghiệp", "url": "https://thanhnien.vn/rss/thoi-trang-tre/thoi-trang-nghe-nghiep.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tận hưởng", "url": "https://thanhnien.vn/rss/thoi-trang-tre/tan-huong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Video", "url": "https://thanhnien.vn/rss/thoi-trang-tre/video.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thư viện thời trang", "url": "https://thanhnien.vn/rss/thoi-trang-tre/thu-vien-thoi-trang.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Bạn đọc", "url": "https://thanhnien.vn/rss/ban-doc.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Lá thư tâm sự", "url": "https://thanhnien.vn/rss/ban-doc/la-thu-tam-su.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Từ đơn thư bạn đọc", "url": "https://thanhnien.vn/rss/ban-doc/tu-don-thu-ban-doc.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Hỏi và đáp", "url": "https://thanhnien.vn/rss/ban-doc/hoi-va-dap.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Bạn đọc viết", "url": "https://thanhnien.vn/rss/ban-doc/ban-doc-viet.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Cơ quan chưa trả lời bạn đọc", "url": "https://thanhnien.vn/rss/ban-doc/co-quan-chua-tra-loi-ban-doc.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Trả lời bạn đọc", "url": "https://thanhnien.vn/rss/ban-doc/tra-loi-ban-doc.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Lá lành đùm lá rách", "url": "https://thanhnien.vn/rss/ban-doc/la-lanh-dum-la-rach.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tấm lòng vàng", "url": "https://thanhnien.vn/rss/ban-doc/tam-long-vang.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Rao vặt", "url": "https://thanhnien.vn/rss/rao-vat.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Video", "url": "https://thanhnien.vn/rss/video.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thời sự", "url": "https://thanhnien.vn/rss/video/thoi-su.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Đời sống", "url": "https://thanhnien.vn/rss/video/doi-song.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Giải trí", "url": "https://thanhnien.vn/rss/video/giai-tri.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Giáo dục", "url": "https://thanhnien.vn/rss/video/giao-duc.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Sức khỏe", "url": "https://thanhnien.vn/rss/video/suc-khoe.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thế giới", "url": "https://thanhnien.vn/rss/video/the-gioi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Trải nghiệm số", "url": "https://thanhnien.vn/rss/video/trai-nghiem-so.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - World Cup 2026", "url": "https://thanhnien.vn/rss/video/world-cup-2026.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thể thao", "url": "https://thanhnien.vn/rss/video/the-thao.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Bí quyết ôn thi tốt nghiệp THPT", "url": "https://thanhnien.vn/rss/video/bi-quyet-on-thi-tot-nghiep-thpt.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Phim ngắn Vietnamese", "url": "https://thanhnien.vn/rss/video/phim-ngan-vietnamese.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Trực tuyến", "url": "https://thanhnien.vn/rss/video/truc-tuyen.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Bóng đá  Sinh viên", "url": "https://thanhnien.vn/rss/video/bong-da-thanh-nien-sinh-vien.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Diễn đàn", "url": "https://thanhnien.vn/rss/dien-dan.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Văn hóa giao thông", "url": "https://thanhnien.vn/rss/dien-dan/van-hoa-giao-thong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Podcast", "url": "https://thanhnien.vn/rss/podcast.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - GenZ", "url": "https://thanhnien.vn/rss/podcast/genz.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Showbiz", "url": "https://thanhnien.vn/rss/podcast/showbiz.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Nhật ký Tết Việt", "url": "https://thanhnien.vn/rss/nhat-ky-tet-viet.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Magazine", "url": "https://thanhnien.vn/rss/magazine.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Cùng con đi tiếp cuộc đời", "url": "https://thanhnien.vn/rss/cung-con-di-tiep-cuoc-doi.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Bạn cần biết", "url": "https://thanhnien.vn/rss/ban-can-biet.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Miền Bắc", "url": "https://thanhnien.vn/rss/ban-can-biet/mien-bac.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Miền Nam", "url": "https://thanhnien.vn/rss/ban-can-biet/mien-nam.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Miền Trung", "url": "https://thanhnien.vn/rss/ban-can-biet/mien-trung.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Sản phẩm", "url": "https://thanhnien.vn/rss/ban-can-biet/san-pham.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Dịch vụ", "url": "https://thanhnien.vn/rss/ban-can-biet/dich-vu.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Giải thưởng", "url": "https://thanhnien.vn/rss/ban-can-biet/giai-thuong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Thông báo", "url": "https://thanhnien.vn/rss/ban-can-biet/thong-bao.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Giải trí", "url": "https://thanhnien.vn/rss/ban-can-biet/giai-tri.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tuyển dụng", "url": "https://thanhnien.vn/rss/ban-can-biet/tuyen-dung.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Cải chính", "url": "https://thanhnien.vn/rss/cai-chinh.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Blog phóng viên", "url": "https://thanhnien.vn/rss/blog-phong-vien.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tôi viết", "url": "https://thanhnien.vn/rss/toi-viet.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Việc làm", "url": "https://thanhnien.vn/rss/viec-lam.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - TNO", "url": "https://thanhnien.vn/rss/tno.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tin 24h", "url": "https://thanhnien.vn/rss/tin-24h.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tin thị trường", "url": "https://thanhnien.vn/rss/thi-truong.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Tin nhanh 360", "url": "https://thanhnien.vn/rss/tin-nhanh-360.rss", "source_type": "RSS"},
    {"name": "Thanh Niên - Rss.Html", "url": "https://thanhnien.vn/rss.html", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Trang chủ", "url": "https://tuoitre.vn/home.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Thời sự", "url": "https://tuoitre.vn/thoi-su.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Thế giới", "url": "https://tuoitre.vn/the-gioi.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Pháp luật", "url": "https://tuoitre.vn/phap-luat.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Kinh doanh", "url": "https://tuoitre.vn/kinh-doanh.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Công nghệ", "url": "https://tuoitre.vn/nhip-song-so.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Xe", "url": "https://tuoitre.vn/xe.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Nhịp sống trẻ", "url": "https://tuoitre.vn/nhip-song-tre.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Văn hóa", "url": "https://tuoitre.vn/van-hoa.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Giải trí", "url": "https://tuoitre.vn/giai-tri.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Thể thao", "url": "https://tuoitre.vn/the-thao.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Giáo dục", "url": "https://tuoitre.vn/giao-duc.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Khoa học", "url": "https://tuoitre.vn/khoa-hoc.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Sức khỏe", "url": "https://tuoitre.vn/suc-khoe.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Giả thật", "url": "https://tuoitre.vn/gia-that.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Thư giãn", "url": "https://tuoitre.vn/thu-gian.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Bạn đọc", "url": "https://tuoitre.vn/ban-doc.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Du lịch", "url": "https://tuoitre.vn/du-lich.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Video", "url": "https://tuoitre.vn/video.rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Khái niệm", "url": "https://tuoitre.vn/rss", "source_type": "RSS"},
    {"name": "Tuổi Trẻ - Rss.Htm", "url": "https://tuoitre.vn/rss.htm", "source_type": "RSS"},
    {"name": "Báo Lao Động - Trang chủ", "url": "https://laodong.vn/rss/home.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Thời sự", "url": "https://laodong.vn/rss/thoi-su.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Công đoàn", "url": "https://laodong.vn/rss/cong-doan.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Thế giới", "url": "https://laodong.vn/rss/the-gioi.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Xã hội", "url": "https://laodong.vn/rss/xa-hoi.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Pháp luật", "url": "https://laodong.vn/rss/phap-luat.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Kinh doanh", "url": "https://laodong.vn/rss/kinh-doanh.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Bất động sản", "url": "https://laodong.vn/rss/bat-dong-san.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Văn hóa - Giải trí", "url": "https://laodong.vn/rss/van-hoa-giai-tri.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Thể thao", "url": "https://laodong.vn/rss/the-thao.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Xe+", "url": "https://laodong.vn/rss/xe.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Sức khỏe", "url": "https://laodong.vn/rss/suc-khoe.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Bạn đọc", "url": "https://laodong.vn/rss/ban-doc.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Tấm lòng vàng", "url": "https://laodong.vn/rss/tam-long-vang.rss", "source_type": "RSS"},
    {"name": "Báo Lao Động - Rss", "url": "https://laodong.vn/rss", "source_type": "RSS"},
    {"name": "VTV - Trang chủ", "url": "https://vtv.vn/rss/home.rss", "source_type": "RSS"},
    {"name": "VTV - Vươn mình bằng AI", "url": "https://vtv.vn/rss/vuon-minh-bang-ai.rss", "source_type": "RSS"},
    {"name": "VTV - Thời đại AI", "url": "https://vtv.vn/rss/vuon-minh-bang-ai/thoi-dai-ai.rss", "source_type": "RSS"},
    {"name": "VTV - Doanh nghiệp thời AI", "url": "https://vtv.vn/rss/vuon-minh-bang-ai/doanh-nghiep-thoi-ai.rss", "source_type": "RSS"},
    {"name": "VTV - Góc nhìn AI", "url": "https://vtv.vn/rss/vuon-minh-bang-ai/goc-nhin-ai.rss", "source_type": "RSS"},
    {"name": "VTV - Kiến thức & Đào tạo AI", "url": "https://vtv.vn/rss/vuon-minh-bang-ai/kien-thuc-dao-tao-ai.rss", "source_type": "RSS"},
    {"name": "VTV - Golf", "url": "https://vtv.vn/rss/golf.rss", "source_type": "RSS"},
    {"name": "VTV - Chính trị", "url": "https://vtv.vn/rss/chinh-tri.rss", "source_type": "RSS"},
    {"name": "VTV - Alo  Times", "url": "https://vtv.vn/rss/alo-vtv-times.rss", "source_type": "RSS"},
    {"name": "VTV - Góc phản ánh", "url": "https://vtv.vn/rss/alo-vtv-times/goc-phan-anh.rss", "source_type": "RSS"},
    {"name": "VTV - Phóng sự điều tra", "url": "https://vtv.vn/rss/alo-vtv-times/phong-su-dieu-tra.rss", "source_type": "RSS"},
    {"name": "VTV - Thể thao", "url": "https://vtv.vn/rss/the-thao.rss", "source_type": "RSS"},
    {"name": "VTV - Xã hội", "url": "https://vtv.vn/rss/xa-hoi.rss", "source_type": "RSS"},
    {"name": "VTV - Pháp luật", "url": "https://vtv.vn/rss/phap-luat.rss", "source_type": "RSS"},
    {"name": "VTV - Thế giới", "url": "https://vtv.vn/rss/the-gioi.rss", "source_type": "RSS"},
    {"name": "VTV - Tin tức", "url": "https://vtv.vn/rss/the-gioi/tin-tuc.rss", "source_type": "RSS"},
    {"name": "VTV - Thế giới đó đây", "url": "https://vtv.vn/rss/the-gioi/the-gioi-do-day.rss", "source_type": "RSS"},
    {"name": "VTV - Câu chuyện quốc tế", "url": "https://vtv.vn/rss/the-gioi/cau-chuyen-quoc-te.rss", "source_type": "RSS"},
    {"name": "VTV - Người Việt bốn phương", "url": "https://vtv.vn/rss/the-gioi/nguoi-viet-bon-phuong.rss", "source_type": "RSS"},
    {"name": "VTV - Kinh tế", "url": "https://vtv.vn/rss/kinh-te.rss", "source_type": "RSS"},
    {"name": "VTV - Tài chính", "url": "https://vtv.vn/rss/kinh-te/tai-chinh.rss", "source_type": "RSS"},
    {"name": "VTV - Thị trường", "url": "https://vtv.vn/rss/kinh-te/thi-truong.rss", "source_type": "RSS"},
    {"name": "VTV - Góc doanh nghiệp", "url": "https://vtv.vn/rss/kinh-te/goc-doanh-nghiep.rss", "source_type": "RSS"},
    {"name": "VTV - Truyền hình", "url": "https://vtv.vn/rss/truyen-hinh.rss", "source_type": "RSS"},
    {"name": "VTV - Phim", "url": "https://vtv.vn/rss/truyen-hinh/phim-vtv.rss", "source_type": "RSS"},
    {"name": "VTV - Hậu trường", "url": "https://vtv.vn/rss/truyen-hinh/hau-truong.rss", "source_type": "RSS"},
    {"name": "VTV - Nhân vật", "url": "https://vtv.vn/rss/truyen-hinh/nhan-vat.rss", "source_type": "RSS"},
    {"name": "VTV - Góc khán giả", "url": "https://vtv.vn/rss/truyen-hinh/goc-khan-gia.rss", "source_type": "RSS"},
    {"name": "VTV - Điểm hẹn tài năng", "url": "https://vtv.vn/rss/truyen-hinh/diem-hen-tai-nang.rss", "source_type": "RSS"},
    {"name": "VTV - Giải Sao Mai", "url": "https://vtv.vn/rss/truyen-hinh/giai-sao-mai.rss", "source_type": "RSS"},
    {"name": "VTV - Văn hóa - Giải trí", "url": "https://vtv.vn/rss/van-hoa-giai-tri.rss", "source_type": "RSS"},
    {"name": "VTV - Điện ảnh", "url": "https://vtv.vn/rss/van-hoa-giai-tri/dien-anh.rss", "source_type": "RSS"},
    {"name": "VTV - Âm nhạc", "url": "https://vtv.vn/rss/van-hoa-giai-tri/am-nhac.rss", "source_type": "RSS"},
    {"name": "VTV - Sao", "url": "https://vtv.vn/rss/van-hoa-giai-tri/sao.rss", "source_type": "RSS"},
    {"name": "VTV - Đời sống", "url": "https://vtv.vn/rss/doi-song.rss", "source_type": "RSS"},
    {"name": "VTV - Du lịch", "url": "https://vtv.vn/rss/doi-song/du-lich.rss", "source_type": "RSS"},
    {"name": "VTV - Làm đẹp", "url": "https://vtv.vn/rss/doi-song/lam-dep.rss", "source_type": "RSS"},
    {"name": "VTV - Chất lượng cuộc sống", "url": "https://vtv.vn/rss/doi-song/chat-luong-cuoc-song.rss", "source_type": "RSS"},
    {"name": "VTV - Công nghệ", "url": "https://vtv.vn/rss/cong-nghe.rss", "source_type": "RSS"},
    {"name": "VTV - Cuộc sống số", "url": "https://vtv.vn/rss/cong-nghe/cuoc-song-so.rss", "source_type": "RSS"},
    {"name": "VTV - HiTech Công nghệ tương lai", "url": "https://vtv.vn/rss/cong-nghe/hitech-cong-nghe-tuong-lai.rss", "source_type": "RSS"},
    {"name": "VTV - Sản phẩm", "url": "https://vtv.vn/rss/cong-nghe/san-pham.rss", "source_type": "RSS"},
    {"name": "VTV - Thị trường", "url": "https://vtv.vn/rss/cong-nghe/thi-truong.rss", "source_type": "RSS"},
    {"name": "VTV - Tư vấn", "url": "https://vtv.vn/rss/cong-nghe/tu-van.rss", "source_type": "RSS"},
    {"name": "VTV - Khoa học & Công nghệ", "url": "https://vtv.vn/rss/cong-nghe/khoa-hoc-cong-nghe.rss", "source_type": "RSS"},
    {"name": "VTV - Bình dân học vụ số", "url": "https://vtv.vn/rss/cong-nghe/binh-dan-hoc-vu-so.rss", "source_type": "RSS"},
    {"name": "VTV - Trí tuệ nhân tạo", "url": "https://vtv.vn/rss/cong-nghe/tri-tue-nhan-tao.rss", "source_type": "RSS"},
    {"name": "VTV - Bán dẫn", "url": "https://vtv.vn/rss/cong-nghe/ban-dan.rss", "source_type": "RSS"},
    {"name": "VTV - An ninh mạng", "url": "https://vtv.vn/rss/cong-nghe/an-ninh-mang.rss", "source_type": "RSS"},
    {"name": "VTV - Xe", "url": "https://vtv.vn/rss/cong-nghe/xe.rss", "source_type": "RSS"},
    {"name": "VTV - Giáo dục", "url": "https://vtv.vn/rss/giao-duc.rss", "source_type": "RSS"},
    {"name": "VTV - Tư vấn", "url": "https://vtv.vn/rss/giao-duc/tu-van.rss", "source_type": "RSS"},
    {"name": "VTV - Học trực tuyến", "url": "https://vtv.vn/rss/giao-duc/hoc-truc-tuyen.rss", "source_type": "RSS"},
    {"name": "VTV - Tuyển sinh", "url": "https://vtv.vn/rss/giao-duc/tuyen-sinh.rss", "source_type": "RSS"},
    {"name": "VTV - Trực tuyến", "url": "https://vtv.vn/rss/truc-tuyen.rss", "source_type": "RSS"},
    {"name": "VTV - Thư viện ảnh", "url": "https://vtv.vn/rss/thu-vien-anh.rss", "source_type": "RSS"},
    {"name": "VTV - Chương trình đặc sắc", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac.rss", "source_type": "RSS"},
    {"name": "VTV - 90 phút để hiểu", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/90-phut-de-hieu.rss", "source_type": "RSS"},
    {"name": "VTV - Sống mới", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/song-moi.rss", "source_type": "RSS"},
    {"name": "VTV - Nhịp sống đô thị", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/nhip-song-do-thi.rss", "source_type": "RSS"},
    {"name": "VTV - Doanh nhân và hội nhập", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/doanh-nhan-va-hoi-nhap.rss", "source_type": "RSS"},
    {"name": "VTV - Chuyện nhà nông với nông nghiệp", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/chuyen-nha-nong-voi-nong-nghiep.rss", "source_type": "RSS"},
    {"name": "VTV - Sự kiện và bình luận", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/su-kien-va-binh-luan.rss", "source_type": "RSS"},
    {"name": "VTV - Mỗi ngày một cuốn sách", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/moi-ngay-mot-cuon-sach.rss", "source_type": "RSS"},
    {"name": "VTV - Đảng trong cuộc sống hôm nay", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/dang-trong-cuoc-song-hom-nay.rss", "source_type": "RSS"},
    {"name": "VTV - Chính sách kinh tế và cuộc sống", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/chinh-sach-kinh-te-va-cuoc-song.rss", "source_type": "RSS"},
    {"name": "VTV - Toàn cảnh thế giới", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/toan-canh-the-gioi.rss", "source_type": "RSS"},
    {"name": "VTV - Đối thoại chính sách", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/doi-thoai-chinh-sach.rss", "source_type": "RSS"},
    {"name": "VTV - Tiêu điểm", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/tieu-diem.rss", "source_type": "RSS"},
    {"name": "VTV - Tạp chí kinh tế cuối tuần", "url": "https://vtv.vn/rss/chuong-trinh-dac-sac/tap-chi-kinh-te-cuoi-tuan.rss", "source_type": "RSS"},
    {"name": "VTV - Video đặc sắc", "url": "https://vtv.vn/rss/video-dac-sac.rss", "source_type": "RSS"},
    {"name": "VTV - Hoạt động", "url": "https://vtv.vn/rss/hoat-dong-vtv.rss", "source_type": "RSS"},
    {"name": "VTV - Telefilm 2018", "url": "https://vtv.vn/rss/hoat-dong-vtv/telefilm-2018.rss", "source_type": "RSS"},
    {"name": "VTV - Thông cáo báo chí", "url": "https://vtv.vn/rss/hoat-dong-vtv/thong-cao-bao-chi.rss", "source_type": "RSS"},
    {"name": "VTV - Cơ hội nghề nghiệp", "url": "https://vtv.vn/rss/hoat-dong-vtv/co-hoi-nghe-nghiep.rss", "source_type": "RSS"},
    {"name": "VTV - Tin tức sự kiện", "url": "https://vtv.vn/rss/hoat-dong-vtv/tin-tuc-su-kien.rss", "source_type": "RSS"},
    {"name": "VTV - World Cup 2026™", "url": "https://vtv.vn/rss/world-cup-2026.rss", "source_type": "RSS"},
    {"name": "VTV - Tin nhanh World Cup", "url": "https://vtv.vn/rss/world-cup-2026/tin-nhanh-world-cup.rss", "source_type": "RSS"},
    {"name": "VTV - Match center", "url": "https://vtv.vn/rss/world-cup-2026/match-center.rss", "source_type": "RSS"},
    {"name": "VTV - Fanzone", "url": "https://vtv.vn/rss/world-cup-2026/fanzone.rss", "source_type": "RSS"},
    {"name": "VTV - Chương trình đã phát sóng", "url": "https://vtv.vn/rss/chuong-trinh-da-phat-song.rss", "source_type": "RSS"},
    {"name": "VTV - Vấn đề hôm nay", "url": "https://vtv.vn/rss/van-de-hom-nay.rss", "source_type": "RSS"},
    {"name": "VTV - Đại hội Đảng", "url": "https://vtv.vn/rss/dai-hoi-dang.rss", "source_type": "RSS"},
    {"name": "VTV - Tổng Bí thư Tô Lâm", "url": "https://vtv.vn/rss/dai-hoi-dang/tong-bi-thu-to-lam.rss", "source_type": "RSS"},
    {"name": "VTV - Video", "url": "https://vtv.vn/rss/dai-hoi-dang/video.rss", "source_type": "RSS"},
    {"name": "VTV - Ảnh", "url": "https://vtv.vn/rss/dai-hoi-dang/anh.rss", "source_type": "RSS"},
    {"name": "VTV - Hỏi đáp", "url": "https://vtv.vn/rss/dai-hoi-dang/hoi-dap.rss", "source_type": "RSS"},
    {"name": "VTV - Các kỳ Đại hội Đảng", "url": "https://vtv.vn/rss/dai-hoi-dang/cac-ky-dai-hoi-dang.rss", "source_type": "RSS"},
    {"name": "VTV - Đảng bộ Ban, Bộ, Ngành các cơ quan Trung ương", "url": "https://vtv.vn/rss/dai-hoi-dang/dang-bo-ban-bo-nganh-cac-co-quan-trung-uong.rss", "source_type": "RSS"},
    {"name": "VTV - Đại hội Đảng bộ trực thuộc Trung ương", "url": "https://vtv.vn/rss/dai-hoi-dang/dai-hoi-dang-bo-truc-thuoc-trung-uong.rss", "source_type": "RSS"},
    {"name": "VTV - Đại hội Đảng toàn quốc", "url": "https://vtv.vn/rss/dai-hoi-dang/dai-hoi-dang-toan-quoc.rss", "source_type": "RSS"},
    {"name": "VTV - Đại hội Đảng bộ tỉnh, thành phố", "url": "https://vtv.vn/rss/dai-hoi-dang/dai-hoi-dang-bo-tinh-thanh-pho.rss", "source_type": "RSS"},
    {"name": "VTV - Đại hội Đảng bộ các cấp cơ sở", "url": "https://vtv.vn/rss/dai-hoi-dang/dai-hoi-dang-bo-cac-cap-co-so.rss", "source_type": "RSS"},
    {"name": "VTV - Y tế", "url": "https://vtv.vn/rss/y-te.rss", "source_type": "RSS"},
    {"name": "VTV - PODCAST", "url": "https://vtv.vn/rss/podcast.rss", "source_type": "RSS"},
    {"name": "VTV - Ơi nghe nè", "url": "https://vtv.vn/rss/podcast/oi-nghe-ne.rss", "source_type": "RSS"},
    {"name": "VTV - Đối thoại trực tuyến", "url": "https://vtv.vn/rss/podcast/doi-thoai-truc-tuyen.rss", "source_type": "RSS"},
    {"name": "VTV - Nhịp sống 24h", "url": "https://vtv.vn/rss/podcast/nhip-song-24h.rss", "source_type": "RSS"},
    {"name": "VTV - Thời sự hằng ngày", "url": "https://vtv.vn/rss/podcast/thoi-su-hang-ngay.rss", "source_type": "RSS"},
    {"name": "VTV - Tâm sự đêm", "url": "https://vtv.vn/rss/podcast/tam-su-dem.rss", "source_type": "RSS"},
    {"name": "VTV - Hạt giống tâm hồn", "url": "https://vtv.vn/rss/podcast/hat-giong-tam-hon.rss", "source_type": "RSS"},
    {"name": "VTV - Tấm lòng Việt", "url": "https://vtv.vn/rss/tam-long-viet.rss", "source_type": "RSS"},
    {"name": "VTV - 55 năm", "url": "https://vtv.vn/rss/55-nam-vtv.rss", "source_type": "RSS"},
    {"name": "VTV - Tin tức", "url": "https://vtv.vn/rss/55-nam-vtv/tin-tuc.rss", "source_type": "RSS"},
    {"name": "VTV - Chương trình dấu ấn", "url": "https://vtv.vn/rss/55-nam-vtv/chuong-trinh-dau-an.rss", "source_type": "RSS"},
    {"name": "VTV - Ký ức", "url": "https://vtv.vn/rss/55-nam-vtv/ky-uc-vtv.rss", "source_type": "RSS"},
    {"name": "VTV - Gương mặt", "url": "https://vtv.vn/rss/55-nam-vtv/guong-mat-vtv.rss", "source_type": "RSS"},
    {"name": "VTV - Ngày ấy – Bây giờ", "url": "https://vtv.vn/rss/55-nam-vtv/ngay-ay-bay-gio.rss", "source_type": "RSS"},
    {"name": "VTV - Video", "url": "https://vtv.vn/rss/55-nam-vtv/video.rss", "source_type": "RSS"},
    {"name": "VTV - trong tôi", "url": "https://vtv.vn/rss/55-nam-vtv/vtv-trong-toi.rss", "source_type": "RSS"},
    {"name": "VTV - Dữ liệu và Đời sống", "url": "https://vtv.vn/rss/du-lieu-va-doi-song.rss", "source_type": "RSS"},
    {"name": "VTV - Kỷ nguyên Dữ liệu", "url": "https://vtv.vn/rss/du-lieu-va-doi-song/ky-nguyen-du-lieu.rss", "source_type": "RSS"},
    {"name": "VTV - Khoa học Dữ liệu", "url": "https://vtv.vn/rss/du-lieu-va-doi-song/khoa-hoc-du-lieu.rss", "source_type": "RSS"},
    {"name": "VTV - Số liệu quanh ta", "url": "https://vtv.vn/rss/du-lieu-va-doi-song/so-lieu-quanh-ta.rss", "source_type": "RSS"},
    {"name": "VTV - SEA Games 33", "url": "https://vtv.vn/rss/sea-games-33.rss", "source_type": "RSS"},
    {"name": "VTV - Điểm nhấn", "url": "https://vtv.vn/rss/diem-nhan.rss", "source_type": "RSS"},
    {"name": "VTV - V-zine", "url": "https://vtv.vn/rss/magazine.rss", "source_type": "RSS"},
    {"name": "VTV - Infographic", "url": "https://vtv.vn/rss/infographic.rss", "source_type": "RSS"},
    {"name": "VOV - Rss", "url": "https://vov.gov.vn/Rss/RssPage", "source_type": "RSS"},
    {"name": "VOV - Rss theo chủ đề của cổng", "url": "https://vov.gov.vn/rss/RssCategory", "source_type": "RSS"},
    {"name": "VOV - Rss theo chuyên đề", "url": "https://vov.gov.vn/Rss/RssChuyende", "source_type": "RSS"},
    {"name": "VOV - Rss theo các ban", "url": "https://vov.gov.vn/Rss/RssTheoBan", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Trang chủ", "url": "https://baoxaydung.vn/rss/home.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thời sự", "url": "https://baoxaydung.vn/rss/thoi-su.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Chính trị", "url": "https://baoxaydung.vn/rss/thoi-su/chinh-tri.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Xã hội", "url": "https://baoxaydung.vn/rss/thoi-su/xa-hoi.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Chuyện dọc đường", "url": "https://baoxaydung.vn/rss/thoi-su/chuyen-doc-duong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Cải chính", "url": "https://baoxaydung.vn/rss/thoi-su/cai-chinh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Giao thông", "url": "https://baoxaydung.vn/rss/giao-thong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Quản lý", "url": "https://baoxaydung.vn/rss/giao-thong/quan-ly.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đường bộ", "url": "https://baoxaydung.vn/rss/giao-thong/duong-bo.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Hàng không", "url": "https://baoxaydung.vn/rss/giao-thong/hang-khong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đường sắt", "url": "https://baoxaydung.vn/rss/giao-thong/duong-sat.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đường sắt tốc độ cao", "url": "https://baoxaydung.vn/rss/giao-thong/duong-sat-toc-do-cao.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đường sắt đô thị", "url": "https://baoxaydung.vn/rss/giao-thong/duong-sat-do-thi.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đường thủy", "url": "https://baoxaydung.vn/rss/giao-thong/duong-thuy.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đăng kiểm", "url": "https://baoxaydung.vn/rss/giao-thong/dang-kiem.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Hàng hải", "url": "https://baoxaydung.vn/rss/giao-thong/hang-hai.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Mời thầu - Đấu thầu", "url": "https://baoxaydung.vn/rss/giao-thong/moi-thau-dau-thau.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thi viết về Ngành", "url": "https://baoxaydung.vn/rss/giao-thong/thi-viet-ve-nganh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Xây dựng", "url": "https://baoxaydung.vn/rss/xay-dung.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Chỉ đạo điều hành", "url": "https://baoxaydung.vn/rss/xay-dung/chi-dao-dieu-hanh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Quy hoạch kiến trúc", "url": "https://baoxaydung.vn/rss/xay-dung/quy-hoach-kien-truc.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Vật liệu xây dựng", "url": "https://baoxaydung.vn/rss/xay-dung/vat-lieu-xay-dung.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Giám định chất lượng", "url": "https://baoxaydung.vn/rss/xay-dung/giam-dinh-chat-luong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Quản lý đô thị", "url": "https://baoxaydung.vn/rss/xay-dung/quan-ly-do-thi.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Kinh tế", "url": "https://baoxaydung.vn/rss/kinh-te.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thị trường", "url": "https://baoxaydung.vn/rss/kinh-te/thi-truong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Tài chính", "url": "https://baoxaydung.vn/rss/kinh-te/tai-chinh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Chứng khoán", "url": "https://baoxaydung.vn/rss/kinh-te/chung-khoan.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Bảo hiểm", "url": "https://baoxaydung.vn/rss/kinh-te/bao-hiem.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Doanh nghiệp", "url": "https://baoxaydung.vn/rss/kinh-te/doanh-nghiep.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đất đai", "url": "https://baoxaydung.vn/rss/kinh-te/dat-dai-va-moi-truong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Môi trường", "url": "https://baoxaydung.vn/rss/kinh-te/moi-truong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Bất động sản", "url": "https://baoxaydung.vn/rss/bat-dong-san.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Chính sách", "url": "https://baoxaydung.vn/rss/bat-dong-san/chinh-sach.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Quy hoạch - Hạ tầng", "url": "https://baoxaydung.vn/rss/bat-dong-san/quy-hoach-ha-tang.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đối thoại", "url": "https://baoxaydung.vn/rss/bat-dong-san/doi-thoai.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Nhà đầu tư", "url": "https://baoxaydung.vn/rss/bat-dong-san/nha-dau-tu.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thị trường", "url": "https://baoxaydung.vn/rss/bat-dong-san/thi-truong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Dự án", "url": "https://baoxaydung.vn/rss/bat-dong-san/du-an.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Nội thất - Ngoại thất", "url": "https://baoxaydung.vn/rss/bat-dong-san/noi-that-ngoai-that.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Nhà đẹp", "url": "https://baoxaydung.vn/rss/bat-dong-san/nha-dep.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Tư vấn", "url": "https://baoxaydung.vn/rss/bat-dong-san/tu-van.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Video", "url": "https://baoxaydung.vn/rss/bat-dong-san/video.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Pháp luật", "url": "https://baoxaydung.vn/rss/phap-luat.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thanh tra", "url": "https://baoxaydung.vn/rss/phap-luat/thanh-tra.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - An ninh hình sự", "url": "https://baoxaydung.vn/rss/phap-luat/an-ninh-hinh-su.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Điều tra", "url": "https://baoxaydung.vn/rss/phap-luat/dieu-tra.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Pháp đình", "url": "https://baoxaydung.vn/rss/phap-luat/phap-dinh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Hỏi - Đáp", "url": "https://baoxaydung.vn/rss/phap-luat/hoi-dap.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Chất lượng sống", "url": "https://baoxaydung.vn/rss/chat-luong-song.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Giáo dục", "url": "https://baoxaydung.vn/rss/chat-luong-song/giao-duc.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Y tế", "url": "https://baoxaydung.vn/rss/chat-luong-song/y-te.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đời sống", "url": "https://baoxaydung.vn/rss/chat-luong-song/doi-song.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Lao động - Công đoàn", "url": "https://baoxaydung.vn/rss/chat-luong-song/lao-dong-cong-doan.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Văn hóa - Giải Trí", "url": "https://baoxaydung.vn/rss/van-hoa-giai-tri.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Văn hóa", "url": "https://baoxaydung.vn/rss/van-hoa-giai-tri/van-hoa.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Showbiz", "url": "https://baoxaydung.vn/rss/van-hoa-giai-tri/showbiz.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Điện ảnh", "url": "https://baoxaydung.vn/rss/van-hoa-giai-tri/dien-anh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Âm nhạc", "url": "https://baoxaydung.vn/rss/van-hoa-giai-tri/am-nhac.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thể thao", "url": "https://baoxaydung.vn/rss/the-thao.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Bóng đá", "url": "https://baoxaydung.vn/rss/the-thao/bong-da.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Bình luận", "url": "https://baoxaydung.vn/rss/the-thao/binh-luan.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Hậu trường sao", "url": "https://baoxaydung.vn/rss/the-thao/hau-truong-sao.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - 360 độ thể thao", "url": "https://baoxaydung.vn/rss/the-thao/360-do-the-thao.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Công nghệ", "url": "https://baoxaydung.vn/rss/cong-nghe.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Công nghệ mới", "url": "https://baoxaydung.vn/rss/cong-nghe/cong-nghe-moi.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Sản phẩm mới", "url": "https://baoxaydung.vn/rss/cong-nghe/san-pham-moi.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - AI", "url": "https://baoxaydung.vn/rss/cong-nghe/ai.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Tư vấn", "url": "https://baoxaydung.vn/rss/cong-nghe/tu-van.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thế giới", "url": "https://baoxaydung.vn/rss/the-gioi.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thời sự Quốc tế", "url": "https://baoxaydung.vn/rss/the-gioi/tin-quoc-te.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Hồ sơ tài liệu", "url": "https://baoxaydung.vn/rss/the-gioi/ho-so-tai-lieu.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thế giới giao thông", "url": "https://baoxaydung.vn/rss/the-gioi/the-gioi-giao-thong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thế giới xây dựng", "url": "https://baoxaydung.vn/rss/the-gioi/the-gioi-xay-dung.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đi ++", "url": "https://baoxaydung.vn/rss/di.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Du lịch", "url": "https://baoxaydung.vn/rss/di/du-lich.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Khám phá", "url": "https://baoxaydung.vn/rss/di/kham-pha.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Lối sống", "url": "https://baoxaydung.vn/rss/di/loi-song.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Ẩm thực", "url": "https://baoxaydung.vn/rss/di/am-thuc.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Video", "url": "https://baoxaydung.vn/rss/video.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thời sự", "url": "https://baoxaydung.vn/rss/video/video-thoi-su.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Khám phá", "url": "https://baoxaydung.vn/rss/video/kham-pha.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Camera giao thông", "url": "https://baoxaydung.vn/rss/video/camera-giao-thong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Câu chuyện giao thông", "url": "https://baoxaydung.vn/rss/video/cau-chuyen-giao-thong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Lăng kính xây dựng", "url": "https://baoxaydung.vn/rss/video/lang-kinh-xay-dung.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Giải trí - Thể thao", "url": "https://baoxaydung.vn/rss/video/giai-tri-the-thao.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Special", "url": "https://baoxaydung.vn/rss/special.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Emagazine", "url": "https://baoxaydung.vn/rss/emagazine.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Photo", "url": "https://baoxaydung.vn/rss/photo.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Infographic", "url": "https://baoxaydung.vn/rss/infographic.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thông tin doanh nghiệp", "url": "https://baoxaydung.vn/rss/thong-tin-doanh-nghiep.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Bạn cần biết", "url": "https://baoxaydung.vn/rss/ban-can-biet.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Xe", "url": "https://baoxaydung.vn/rss/xe.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - 360° xe", "url": "https://baoxaydung.vn/rss/xe/360-xe.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thị trường xe", "url": "https://baoxaydung.vn/rss/xe/thi-truong-xe.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Đánh giá xe", "url": "https://baoxaydung.vn/rss/xe/danh-gia-xe.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Lái mới", "url": "https://baoxaydung.vn/rss/xe/lai-moi.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Bảo hiểm xe", "url": "https://baoxaydung.vn/rss/xe/bao-hiem-xe.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Xe xanh", "url": "https://baoxaydung.vn/rss/xe/xe-xanh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Video", "url": "https://baoxaydung.vn/rss/xe/video.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Ảnh", "url": "https://baoxaydung.vn/rss/xe/anh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - An toàn giao thông", "url": "https://baoxaydung.vn/rss/an-toan-giao-thong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Giao thông 24h", "url": "https://baoxaydung.vn/rss/an-toan-giao-thong/giao-thong-24h.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - ATGT địa phương", "url": "https://baoxaydung.vn/rss/an-toan-giao-thong/atgt-dia-phuong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Văn hóa giao thông", "url": "https://baoxaydung.vn/rss/an-toan-giao-thong/van-hoa-giao-thong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Lái xe an toàn", "url": "https://baoxaydung.vn/rss/an-toan-giao-thong/lai-xe-an-toan.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Chung tay vì ATGT", "url": "https://baoxaydung.vn/rss/an-toan-giao-thong/chung-tay-vi-atgt.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Gương sáng giao thông", "url": "https://baoxaydung.vn/rss/an-toan-giao-thong/guong-sang-giao-thong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Nhà thầu", "url": "https://baoxaydung.vn/rss/nha-thau.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Cơ hội & Thách thức", "url": "https://baoxaydung.vn/rss/nha-thau/co-hoi-thach-thuc.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Doanh nghiệp dẫn đầu", "url": "https://baoxaydung.vn/rss/nha-thau/doanh-nghiep-dan-dau.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Doanh nghiệp đồng hành", "url": "https://baoxaydung.vn/rss/nha-thau/doanh-nghiep-dong-hanh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thương hiệu nổi bật", "url": "https://baoxaydung.vn/rss/nha-thau/thuong-hieu-noi-bat.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Tổng quan Doanh nghiệp vận tải", "url": "https://baoxaydung.vn/rss/tong-quan-doanh-nghiep-van-tai.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thách thức và cơ hội", "url": "https://baoxaydung.vn/rss/tong-quan-doanh-nghiep-van-tai/thach-thuc-va-co-hoi.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Doanh nghiệp & thương hiệu", "url": "https://baoxaydung.vn/rss/tong-quan-doanh-nghiep-van-tai/doanh-nghiep-thuong-hieu.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Doanh nghiệp đồng hành", "url": "https://baoxaydung.vn/rss/tong-quan-doanh-nghiep-van-tai/doanh-nghiep-dong-hanh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Doanh nghiệp nổi bật", "url": "https://baoxaydung.vn/rss/tong-quan-doanh-nghiep-van-tai/doanh-nghiep-noi-bat.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - English", "url": "https://baoxaydung.vn/rss/english.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Bộ Xây dựng", "url": "https://baoxaydung.vn/rss/bo-xay-dung.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Tin Bộ, ngành", "url": "https://baoxaydung.vn/rss/tin-bo-nganh.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Tin địa phương", "url": "https://baoxaydung.vn/rss/tin-dia-phuong.rss", "source_type": "RSS"},
    {"name": "Báo Xây dựng - Thông tin tòa soạn", "url": "https://baoxaydung.vn/index.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Rss.Html", "url": "https://nhandan.vn/rss.html", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Home", "url": "https://nhandan.vn/rss/home.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Chính trị", "url": "https://nhandan.vn/rss/chinhtri-1171.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Xã luận", "url": "https://nhandan.vn/rss/xa-luan-1176.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Bình luận - Phê phán", "url": "https://nhandan.vn/rss/binh-luan-phe-phan-1180.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Xây dựng Đảng", "url": "https://nhandan.vn/rss/xay-dung-dang-1179.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Kinh tế", "url": "https://nhandan.vn/rss/kinhte-1185.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Tài chính – Chứng khoán", "url": "https://nhandan.vn/rss/chungkhoan-1191.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Thông tin hàng hóa", "url": "https://nhandan.vn/rss/thong-tin-hang-hoa-1203.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Văn hóa", "url": "https://nhandan.vn/rss/vanhoa-1251.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Xã hội", "url": "https://nhandan.vn/rss/xahoi-1211.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - BHXH và cuộc sống", "url": "https://nhandan.vn/rss/bhxh-va-cuoc-song-1222.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Người tốt việc tốt", "url": "https://nhandan.vn/rss/nguoi-tot-viec-tot-1319.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Pháp luật", "url": "https://nhandan.vn/rss/phapluat-1287.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Du lịch", "url": "https://nhandan.vn/rss/du-lich-1257.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Thế giới", "url": "https://nhandan.vn/rss/thegioi-1231.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Bình luận quốc tế", "url": "https://nhandan.vn/rss/binh-luan-quoc-te-1236.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - ASEAN", "url": "https://nhandan.vn/rss/asean-704471.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Châu Phi", "url": "https://nhandan.vn/rss/chau-phi-704476.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Châu Mỹ", "url": "https://nhandan.vn/rss/chau-my-704475.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Châu Âu", "url": "https://nhandan.vn/rss/chau-au-704474.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Trung Đông", "url": "https://nhandan.vn/rss/trung-dong-704473.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Châu Á-TBD", "url": "https://nhandan.vn/rss/chau-a-tbd-704472.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Thể thao", "url": "https://nhandan.vn/rss/thethao-1224.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Giáo dục", "url": "https://nhandan.vn/rss/giaoduc-1303.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Y tế", "url": "https://nhandan.vn/rss/y-te-1309.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Góc tư vấn", "url": "https://nhandan.vn/rss/goc-tu-van-1311.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Khoa học - Công nghệ", "url": "https://nhandan.vn/rss/khoahoc-congnghe-1292.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Phòng, chống tội phạm công nghệ cao", "url": "https://nhandan.vn/rss/phong-chong-toi-pham-cong-nghe-cao-2025-704717.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Môi trường", "url": "https://nhandan.vn/rss/moi-truong-1296.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Bạn đọc", "url": "https://nhandan.vn/rss/bandoc-1315.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Đường dây nóng", "url": "https://nhandan.vn/rss/duong-day-nong-1316.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Điều tra qua thư bạn đọc", "url": "https://nhandan.vn/rss/dieu-tra-qua-thu-ban-doc-1317.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Kiểm chứng thông tin", "url": "https://nhandan.vn/rss/factcheck-658978.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Tri thức chuyên sâu", "url": "https://nhandan.vn/rss/tri-thuc-chuyen-sau-704477.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - 54 dân tộc Việt Nam", "url": "https://nhandan.vn/rss/54-dan-toc-704489.rss", "source_type": "RSS"},
    {"name": "Báo Nhân Dân - Chương trình OCOP - Mỗi xã một sản phẩm", "url": "https://nhandan.vn/rss/ocop-704555.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Rss", "url": "https://www.qdnd.vn/rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Trang chủ", "url": "https://www.qdnd.vn/rss/cate/tin-tuc-moi-nhat.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Tic Tuc Moi Nhat", "url": "https://www.qdnd.vn/rss/cate/tic-tuc-moi-nhat.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Noi Nguoi Chien Si Tro Ve 3822", "url": "https://www.qdnd.vn/rss/cate/noi-nguoi-chien-si-tro-ve-3822.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Bau Cu Dai Bieu Quoc Hoi Khoa Xvi 3853", "url": "https://www.qdnd.vn/rss/cate/bau-cu-dai-bieu-quoc-hoi-khoa-xvi-3853.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Cung Ban Luan 3484", "url": "https://www.qdnd.vn/rss/cate/cung-ban-luan-3484.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Dien Dan Chu Nhat 3547", "url": "https://www.qdnd.vn/rss/cate/dien-dan-chu-nhat-3547.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Nhip Cau Ban Doc 3550", "url": "https://www.qdnd.vn/rss/cate/nhip-cau-ban-doc-3550.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Tuong Linh Viet Nam 3757", "url": "https://www.qdnd.vn/rss/cate/tuong-linh-viet-nam-3757.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Cong Nghiep Quoc Phong 4 0 3761", "url": "https://www.qdnd.vn/rss/cate/cong-nghiep-quoc-phong-4-0-3761.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Quan Doi Tien Len Hien Dai 3701", "url": "https://www.qdnd.vn/rss/cate/quan-doi-tien-len-hien-dai-3701.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Cuoc Thi Bao Chi Bao Ve Nen Tang Tu Tuong Cua Dang Trong Tinh Hinh Moi 3702", "url": "https://www.qdnd.vn/rss/cate/cuoc-thi-bao-chi-bao-ve-nen-tang-tu-tuong-cua-dang-trong-tinh-hinh-moi-3702.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Canh Sat Bien Dong Hanh Voi Ngu Dan 3670", "url": "https://www.qdnd.vn/rss/cate/canh-sat-bien-dong-hanh-voi-ngu-dan-3670.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Bao Ve Nen Tang Tu Tuong Cua Dang 3749", "url": "https://www.qdnd.vn/rss/cate/bao-ve-nen-tang-tu-tuong-cua-dang-3749.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Da Phuong Tien 3681", "url": "https://www.qdnd.vn/rss/cate/da-phuong-tien-3681.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Chinh Tri 3429", "url": "https://www.qdnd.vn/rss/cate/chinh-tri-3429.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Quoc Phong An Ninh 3424", "url": "https://www.qdnd.vn/rss/cate/quoc-phong-an-ninh-3424.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Kinh Te 3438", "url": "https://www.qdnd.vn/rss/cate/kinh-te-3438.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Xa Hoi 3442", "url": "https://www.qdnd.vn/rss/cate/xa-hoi-3442.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Giao Duc Khoa Hoc 3558", "url": "https://www.qdnd.vn/rss/cate/giao-duc-khoa-hoc-3558.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Quoc Te 3447", "url": "https://www.qdnd.vn/rss/cate/quoc-te-3447.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Van Hoa 3451", "url": "https://www.qdnd.vn/rss/cate/van-hoa-3451.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - The Thao 3455", "url": "https://www.qdnd.vn/rss/cate/the-thao-3455.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Phong Su Dieu Tra 3462", "url": "https://www.qdnd.vn/rss/cate/phong-su-dieu-tra-3462.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Phap Luat 3543", "url": "https://www.qdnd.vn/rss/cate/phap-luat-3543.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Ban Doc 3466", "url": "https://www.qdnd.vn/rss/cate/ban-doc-3466.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Trang Thanh Pho Ho Chi Minh 3513", "url": "https://www.qdnd.vn/rss/cate/trang-thanh-pho-ho-chi-minh-3513.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Tap Chi Hau Can Quan Doi 3514", "url": "https://www.qdnd.vn/rss/cate/tap-chi-hau-can-quan-doi-3514.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Y Te 3733", "url": "https://www.qdnd.vn/rss/cate/y-te-3733.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Du Lich 3737", "url": "https://www.qdnd.vn/rss/cate/du-lich-3737.rss", "source_type": "RSS"},
    {"name": "Báo Quân đội Nhân dân - Tu Lieu Ho So 3727", "url": "https://www.qdnd.vn/rss/cate/tu-lieu-ho-so-3727.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Rssmain.Html", "url": "https://baodautu.vn/rssMain.html", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Trang Chu", "url": "https://baodautu.vn/trang-chu.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Trang Chu", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/trang-chu.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Thoi Su Dau Tu", "url": "https://baodautu.vn/thoi-su-dau-tu.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Thoi Su Dau Tu", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/thoi-su-dau-tu.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Toan Canh Dau Tu", "url": "https://baodautu.vn/toan-canh-dau-tu.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Toan Canh Dau Tu", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/toan-canh-dau-tu.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Kinh Doanh", "url": "https://baodautu.vn/kinh-doanh.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Kinh Doanh", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/kinh-doanh.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Doanh Nhan", "url": "https://baodautu.vn/doanh-nhan.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Doanh Nhan", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/doanh-nhan.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Ngan Hang  Bao Hiem", "url": "https://baodautu.vn/ngan-hang--bao-hiem.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Ngan Hang  Bao Hiem", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/ngan-hang--bao-hiem.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Dau Tu Tai Chinh", "url": "https://baodautu.vn/dau-tu-tai-chinh.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Dau Tu Tai Chinh", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/dau-tu-tai-chinh.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Thi Truong Dia Oc", "url": "https://baodautu.vn/thi-truong-dia-oc.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Thi Truong Dia Oc", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/thi-truong-dia-oc.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Tieu Dung", "url": "https://baodautu.vn/tieu-dung.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Tieu Dung", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/tieu-dung.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - O To Xe May", "url": "https://baodautu.vn/o-to-xe-may.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - O To Xe May", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/o-to-xe-may.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Khoa Hoc Va Cong Nghe", "url": "https://baodautu.vn/khoa-hoc-va-cong-nghe.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Khoa Hoc Va Cong Nghe", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/khoa-hoc-va-cong-nghe.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Doi Song", "url": "https://baodautu.vn/doi-song.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Doi Song", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/doi-song.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Dau Tu Va Phap Luat", "url": "https://baodautu.vn/dau-tu-va-phap-luat.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Dau Tu Va Phap Luat", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/dau-tu-va-phap-luat.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Thong Tin Doanh Nghiep", "url": "https://baodautu.vn/thong-tin-doanh-nghiep.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Thong Tin Doanh Nghiep", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/thong-tin-doanh-nghiep.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Phat Trien Ben Vung", "url": "https://baodautu.vn/phat-trien-ben-vung.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Phat Trien Ben Vung", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/phat-trien-ben-vung.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Suc Khoe Doanh Nghiep", "url": "https://baodautu.vn/suc-khoe-doanh-nghiep.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Suc Khoe Doanh Nghiep", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/suc-khoe-doanh-nghiep.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Quoc Te", "url": "https://baodautu.vn/quoc-te.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Quoc Te", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/quoc-te.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Du Lich", "url": "https://baodautu.vn/du-lich.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Du Lich", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/du-lich.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Diem Tin Noi Bat", "url": "https://baodautu.vn/diem-tin-noi-bat.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Diem Tin Noi Bat", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/diem-tin-noi-bat.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Kinh Te So", "url": "https://baodautu.vn/kinh-te-so.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Kinh Te So", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/kinh-te-so.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Y Te   Suc Khoe", "url": "https://baodautu.vn/y-te---suc-khoe.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Y Te   Suc Khoe", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/y-te---suc-khoe.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Muc Thong Tin Quang Ba", "url": "https://baodautu.vn/muc-thong-tin-quang-ba.rss", "source_type": "RSS"},
    {"name": "Báo Đầu tư - Muc Thong Tin Quang Ba", "url": "http://add.my.yahoo.com/rss?url=https://baodautu.vn/muc-thong-tin-quang-ba.rss", "source_type": "RSS"},
]



# Default Alert Rules
DEFAULT_ALERT_RULES = [
    {
        "rule_name": "Cảnh báo Khủng hoảng Tiến độ/An toàn/Sự cố (Negative & Critical/High)",
        "condition_query": {
            "sentiment": "NEGATIVE",
            "impact_level": ["CRITICAL", "HIGH"]
        },
        "telegram_chat_id": "default_chat_id",
        "is_active": True
    },
    {
        "rule_name": "Cảnh báo Sự cố Nghiêm trọng (Critical)",
        "condition_query": {
            "impact_level": "CRITICAL"
        },
        "telegram_chat_id": "default_chat_id",
        "is_active": True
    }
]

# Default LLM Configs
DEFAULT_LLM_CONFIGS = [
    {
        "provider": "Google Gemini",
        "model_name": "gemini-3.5-flash",
        "api_key": "",  # Set via UI or GEMINI_API_KEY env var after deploy
        "is_active": True,
        "is_default": True,
        "description": "Google Gemini 3.5 Flash"
    },
    {
        "provider": "Google Gemini",
        "model_name": "gemini-3-flash-preview",
        "api_key": "",  # Set via UI or GEMINI_API_KEY env var after deploy
        "is_active": False,
        "is_default": False,
        "description": "Google Gemini 3.0 Flash (Preview)"
    },
    {
        "provider": "groq",
        "model_name": "llama-3.3-70b-versatile",
        "api_key": "",  # Set via UI or ENV after deploy
        "is_active": True,
        "is_default": False,
        "description": "Groq Llama 3.3 70B Versatile"
    }
]


async def main():
    print(f"Connecting to MongoDB at: {settings.mongodb_uri}")
    client = AsyncIOMotorClient(settings.mongodb_uri)
    db = client[settings.mongodb_database]
    
    # 1. Seed Keywords (idempotent: only insert if it doesn't exist)
    keywords_col = db.keywords
    print("Checking and seeding default keywords...")
    added_kws = 0
    for kw in DEFAULT_KEYWORDS:
        existing = await keywords_col.find_one({"value": kw})
        if not existing:
            doc = {
                "value": kw,
                "is_active": True,
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow()
            }
            await keywords_col.insert_one(doc)
            added_kws += 1
    print(f"✅ Seeding keywords: added {added_kws} new keywords.")

    # 2. Seed Sources (idempotent for url, but updates name if changed)
    sources_col = db.sources
    print("Checking and seeding default sources...")
    added_sources = 0
    updated_sources = 0
    for src in DEFAULT_SOURCES:
        existing = await sources_col.find_one({"url": src["url"]})
        if not existing:
            doc = {
                "name": src["name"],
                "url": src["url"],
                "source_type": src["source_type"],
                "is_active": True,
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow()
            }
            await sources_col.insert_one(doc)
            added_sources += 1
        else:
            if existing.get("name") != src["name"]:
                await sources_col.update_one(
                    {"_id": existing["_id"]},
                    {"$set": {"name": src["name"], "updated_at": datetime.utcnow()}}
                )
                updated_sources += 1
    print(f"✅ Seeding sources: added {added_sources} new sources, updated {updated_sources} source names.")

    # 3. Seed Alert Rules
    alert_rules_col = db.alert_rules
    existing_rules_count = await alert_rules_col.count_documents({})
    if existing_rules_count == 0:
        print(f"Seeding {len(DEFAULT_ALERT_RULES)} default alert rules...")
        rules_docs = [
            {
                "rule_name": rule["rule_name"],
                "condition_query": rule["condition_query"],
                "telegram_chat_id": rule["telegram_chat_id"],
                "is_active": rule["is_active"],
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow()
            } for rule in DEFAULT_ALERT_RULES
        ]
        await alert_rules_col.insert_many(rules_docs)
        print("✅ Alert Rules seeded successfully!")
    else:
        print(f"ℹ️ Alert Rules collection already has {existing_rules_count} items. Skipping seeding.")

    # 4. Seed LLM Configs
    llm_configs_col = db.llm_configs
    print(f"Checking {len(DEFAULT_LLM_CONFIGS)} default LLM configurations...")
    for conf in DEFAULT_LLM_CONFIGS:
        existing = await llm_configs_col.find_one({"model_name": conf["model_name"]})
        if not existing:
            doc = {
                "provider": conf["provider"],
                "model_name": conf["model_name"],
                "api_key": conf["api_key"],
                "is_active": conf["is_active"],
                "is_default": conf["is_default"],
                "description": conf["description"],
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow()
            }
            await llm_configs_col.insert_one(doc)
            print(f"✅ LLM Config seeded: {conf['model_name']}")
        else:
            await llm_configs_col.update_one(
                {"_id": existing["_id"]},
                {"$set": {"is_default": conf["is_default"]}}
            )
            print(f"ℹ️ LLM Config updated (is_default={conf['is_default']}): {conf['model_name']}")

    # 5. Seed / Sync LLM Prompts (always upsert to keep in sync with gemini.py)
    llm_prompts_col = db.llm_prompts
    from app.infrastructure.llm.gemini import SYSTEM_PROMPT, BATCH_SYSTEM_PROMPT
    existing_prompt = await llm_prompts_col.find_one({"is_active": True})
    if existing_prompt:
        await llm_prompts_col.update_one(
            {"_id": existing_prompt["_id"]},
            {
                "$set": {
                    "name": "Prompt CRAFT v2 (Khuyên dùng)",
                    "system_prompt": SYSTEM_PROMPT,
                    "batch_system_prompt": BATCH_SYSTEM_PROMPT,
                    "updated_at": datetime.utcnow(),
                }
            },
        )
        print("✅ LLM Prompt synced (upsert) with latest from gemini.py")
    else:
        default_prompt_doc = {
            "name": "Prompt CRAFT v2 (Khuyên dùng)",
            "system_prompt": SYSTEM_PROMPT,
            "batch_system_prompt": BATCH_SYSTEM_PROMPT,
            "is_active": True,
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow(),
        }
        await llm_prompts_col.insert_one(default_prompt_doc)
        print("✅ Default LLM prompt seeded successfully!")


    # Show final counts
    k_cnt = await keywords_col.count_documents({})
    s_cnt = await sources_col.count_documents({})
    r_cnt = await alert_rules_col.count_documents({})
    l_cnt = await llm_configs_col.count_documents({})
    p_cnt = await llm_prompts_col.count_documents({})
    print(f"Final DB State: {k_cnt} keywords, {s_cnt} sources, {r_cnt} alert rules, {l_cnt} LLM configs, {p_cnt} LLM prompts.")
    client.close()

if __name__ == "__main__":
    asyncio.run(main())
